// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MilkApp.PopulateData.Models
{
    public partial class Milk
    {
        [Key]
        [Column("ID")]
        [StringLength(255)]
        [Unicode(false)]
        public string Id { get; set; }
        [Required]
        [StringLength(255)]
        [Unicode(false)]
        public string Name { get; set; }
        [Required]
        [StringLength(255)]
        [Unicode(false)]
        public string Type { get; set; }
        public int? Storage { get; set; }
    }
}